# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-26 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
