# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-26 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20180126_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='kind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
